// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Execution/ExecutionContext.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Execution.Contracts {

  /// <summary>Holder for reflection information generated from Execution/ExecutionContext.proto</summary>
  public static partial class ExecutionContextReflection {

    #region Descriptor
    /// <summary>File descriptor for Execution/ExecutionContext.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExecutionContextReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBFeGVjdXRpb24vRXhlY3V0aW9uQ29udGV4dC5wcm90bxISZG9saXR0bGUu",
            "ZXhlY3V0aW9uGhRTZWN1cml0eS9DbGFpbS5wcm90byKOAQoQRXhlY3V0aW9u",
            "Q29udGV4dBITCgthcHBsaWNhdGlvbhgBIAEoDBIUCgxtaWNyb3NlcnZpY2UY",
            "AiABKAwSDgoGdGVuYW50GAMgASgMEhUKDWNvcnJlbGF0aW9uSWQYBCABKAwS",
            "KAoGY2xhaW1zGAUgAygLMhguZG9saXR0bGUuc2VjdXJpdHkuQ2xhaW1CH6oC",
            "HERvbGl0dGxlLkV4ZWN1dGlvbi5Db250cmFjdHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Security.Contracts.ClaimReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Execution.Contracts.ExecutionContext), global::Dolittle.Execution.Contracts.ExecutionContext.Parser, new[]{ "Application", "Microservice", "Tenant", "CorrelationId", "Claims" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ExecutionContext : pb::IMessage<ExecutionContext> {
    private static readonly pb::MessageParser<ExecutionContext> _parser = new pb::MessageParser<ExecutionContext>(() => new ExecutionContext());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExecutionContext> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Execution.Contracts.ExecutionContextReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutionContext() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutionContext(ExecutionContext other) : this() {
      application_ = other.application_;
      microservice_ = other.microservice_;
      tenant_ = other.tenant_;
      correlationId_ = other.correlationId_;
      claims_ = other.claims_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutionContext Clone() {
      return new ExecutionContext(this);
    }

    /// <summary>Field number for the "application" field.</summary>
    public const int ApplicationFieldNumber = 1;
    private pb::ByteString application_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Application {
      get { return application_; }
      set {
        application_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "microservice" field.</summary>
    public const int MicroserviceFieldNumber = 2;
    private pb::ByteString microservice_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Microservice {
      get { return microservice_; }
      set {
        microservice_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tenant" field.</summary>
    public const int TenantFieldNumber = 3;
    private pb::ByteString tenant_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Tenant {
      get { return tenant_; }
      set {
        tenant_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "correlationId" field.</summary>
    public const int CorrelationIdFieldNumber = 4;
    private pb::ByteString correlationId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString CorrelationId {
      get { return correlationId_; }
      set {
        correlationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "claims" field.</summary>
    public const int ClaimsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Dolittle.Security.Contracts.Claim> _repeated_claims_codec
        = pb::FieldCodec.ForMessage(42, global::Dolittle.Security.Contracts.Claim.Parser);
    private readonly pbc::RepeatedField<global::Dolittle.Security.Contracts.Claim> claims_ = new pbc::RepeatedField<global::Dolittle.Security.Contracts.Claim>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dolittle.Security.Contracts.Claim> Claims {
      get { return claims_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExecutionContext);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExecutionContext other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Application != other.Application) return false;
      if (Microservice != other.Microservice) return false;
      if (Tenant != other.Tenant) return false;
      if (CorrelationId != other.CorrelationId) return false;
      if(!claims_.Equals(other.claims_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Application.Length != 0) hash ^= Application.GetHashCode();
      if (Microservice.Length != 0) hash ^= Microservice.GetHashCode();
      if (Tenant.Length != 0) hash ^= Tenant.GetHashCode();
      if (CorrelationId.Length != 0) hash ^= CorrelationId.GetHashCode();
      hash ^= claims_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Application.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Application);
      }
      if (Microservice.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Microservice);
      }
      if (Tenant.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Tenant);
      }
      if (CorrelationId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(CorrelationId);
      }
      claims_.WriteTo(output, _repeated_claims_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Application.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Application);
      }
      if (Microservice.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Microservice);
      }
      if (Tenant.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Tenant);
      }
      if (CorrelationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CorrelationId);
      }
      size += claims_.CalculateSize(_repeated_claims_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExecutionContext other) {
      if (other == null) {
        return;
      }
      if (other.Application.Length != 0) {
        Application = other.Application;
      }
      if (other.Microservice.Length != 0) {
        Microservice = other.Microservice;
      }
      if (other.Tenant.Length != 0) {
        Tenant = other.Tenant;
      }
      if (other.CorrelationId.Length != 0) {
        CorrelationId = other.CorrelationId;
      }
      claims_.Add(other.claims_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Application = input.ReadBytes();
            break;
          }
          case 18: {
            Microservice = input.ReadBytes();
            break;
          }
          case 26: {
            Tenant = input.ReadBytes();
            break;
          }
          case 34: {
            CorrelationId = input.ReadBytes();
            break;
          }
          case 42: {
            claims_.AddEntriesFrom(input, _repeated_claims_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
